"""
SmartLib Kiosk - Face Embedding Model
Stores face embeddings for recognition using Deep Neural Networks
"""
from datetime import datetime
from typing import Optional, TYPE_CHECKING
from sqlalchemy import String, DateTime, ForeignKey, Integer, Float
from sqlalchemy.orm import Mapped, mapped_column, relationship
from pgvector.sqlalchemy import Vector

from app.database import Base

if TYPE_CHECKING:
    from app.models.student import Student


class FaceEmbedding(Base):
    """
    Face Embedding model - stores 512-dimensional face vectors.
    
    Generated by ArcFace (InsightFace) deep neural network.
    Used for face verification during student authentication.
    
    Each student can have multiple embeddings (different angles, lighting).
    """
    __tablename__ = "face_embeddings"
    
    # Primary key
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    
    # Foreign key to student
    student_id: Mapped[str] = mapped_column(
        String(20), 
        ForeignKey("students.student_id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    # 512-dimensional embedding vector (using pgvector)
    # ArcFace produces 512-dim normalized vector
    embedding: Mapped[Vector] = mapped_column(Vector(512), nullable=False)
    
    # Embedding metadata
    embedding_version: Mapped[str] = mapped_column(String(20), default="arcface_r100")
    embedding_dim: Mapped[int] = mapped_column(Integer, default=512)
    
    # Hash for quick lookup (SHA256 of embedding)
    embedding_hash: Mapped[Optional[str]] = mapped_column(String(64), nullable=True, index=True)
    
    # Quality score (0-1) - how good the face image was
    quality_score: Mapped[float] = mapped_column(Float, default=1.0)
    
    # Source image path (for debugging/retraining)
    source_image_path: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    
    # Timestamps
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow,
        onupdate=datetime.utcnow
    )
    
    # Relationship to student
    student: Mapped["Student"] = relationship("Student", back_populates="face_embeddings")
    
    def __repr__(self) -> str:
        return f"<FaceEmbedding(id={self.id}, student_id={self.student_id}, version={self.embedding_version})>"
